theme:
  background_color: "#FFFFFF"
  font_color: "#000000"
  font_size: 24
  header_color: "#2E86AB"
  header_font_size: 48
  font: "Helvetica"

slide_order:
  - "slide1.py"
  - "slide2.py"
  - "slide3.py"
